import '../css/Footer.css'

const Footer = () =>{
    return (
        <div className='footer'>
            <p>You can register an email using the email address and an app password.</p>   
            <p>App passwords are generated by the email provider.</p>
            <p>Only works with Gmail accounts at the moment (Planning to add more providers in the future).</p>
            <p>For Gmail, you can generate an app password by following the instructions <a href="https://support.google.com/accounts/answer/185833?hl=en" target="_blank" rel="noreferrer">here</a>.</p>
            <p>By registering your spam emails from the spam folder are going to be deleted automatically every certain amount of time. (Currently the time is set to 3 hours.)</p>
        </div>
    )
}

export default Footer;